function showFormFeedback(element, modifier, message) {
    clearTimeout(element._hideTimer);
    element.textContent = message;
    element.className = 'form-feedback ' + modifier;
    element.hidden = false;
    element.getBoundingClientRect(); // force reflow so fade-in transition plays
    element.classList.add('form-feedback--visible');
    element.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    element._hideTimer = setTimeout(function () {
        element.classList.remove('form-feedback--visible');
        element.addEventListener('transitionend', function hide() {
            element.hidden = true;
            element.removeEventListener('transitionend', hide);
        });
    }, 10000);
}

document.getElementById('contactForm').addEventListener('submit', async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);

    const payload = {
        name: document.getElementById('name').value,
        contact: document.getElementById('contact').value,
        projectType: document.getElementById('projectType').value,
        message: document.getElementById('message').value,
        // This is the token generated by Turnstile
        turnstileToken: formData.get('cf-turnstile-response')
    };

    // 
    const response = await fetch('https://late-pond-aa61.ivan-kuchin-13d.workers.dev', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
    });
    const result = await response.json();

    const form = document.getElementById('contactForm');
    const feedback = document.getElementById('formFeedback');

    if (result.status === "sent") {
        form.reset();
        if (window.turnstile) window.turnstile.reset();
        showFormFeedback(feedback, 'form-feedback--success', "Thank you! Your message has been sent. We'll be in touch soon.");
    } else {
        showFormFeedback(feedback, 'form-feedback--error', "Something went wrong. Please try again or contact us directly.");
    }
});