function showFormFeedback(element, modifier, message) {
    clearTimeout(element._hideTimer);
    element.textContent = message;
    element.className = 'form-feedback ' + modifier;
    element.hidden = false;
    element.getBoundingClientRect(); // force reflow so fade-in transition plays
    element.classList.add('form-feedback--visible');
    element.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    element._hideTimer = setTimeout(function () {
        element.classList.remove('form-feedback--visible');
        element.addEventListener('transitionend', function hide() {
            element.hidden = true;
            element.removeEventListener('transitionend', hide);
        });
    }, 10 * 1000);
}

let currentTheme = getTheme();
document.querySelector('form#contactForm .cf-turnstile').setAttribute('data-theme', currentTheme);


document.getElementById('contactForm').addEventListener('submit', async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);

    const submitBtn = e.target.querySelector('button[type="submit"]');
    const originalText = submitBtn.textContent;
    submitBtn.disabled = true;
    submitBtn.textContent = 'Sending…';
    submitBtn.style.opacity = '0.7';
    submitBtn.style.cursor = 'not-allowed';

    const payload = {
        name: document.getElementById('name').value,
        contact: document.getElementById('contact').value,
        projectType: document.getElementById('projectType').value,
        package: document.getElementById('package').value,
        message: document.getElementById('message').value,
        // This is the token generated by Turnstile
        turnstileToken: formData.get('cf-turnstile-response')
    };

    const form = document.getElementById('contactForm');
    const feedback = document.getElementById('formFeedback');

    try {
        const response = await fetch('https://order-form.ivan-kuchin-13d.workers.dev', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        const result = await response.json();

        if (result.status === "sent") {
            let currentRate = document.querySelector("select#package").value;
            form.reset();
            document.querySelector("select#package").value = currentRate; // reset to current rate after form reset

            if (window.turnstile) window.turnstile.reset();
            showFormFeedback(feedback, 'form-feedback--success', "Thank you! Your message has been sent. We'll be in touch soon.");
        } else {
            console.error('Turnstile returned error:', result);
            showFormFeedback(feedback, 'form-feedback--error', "CAPTCHA verification failed. Please try again or contact us directly.");
        }
    } catch (_err) {
        console.error('Fetch error to the turnstile server:', _err);
        showFormFeedback(feedback, 'form-feedback--error', "Something went wrong. Please try again or contact us directly.");
    } finally {
        // Restore button regardless of outcome
        submitBtn.disabled = false;
        submitBtn.textContent = originalText;
        submitBtn.style.opacity = '';
        submitBtn.style.cursor = '';
    }
});

(function () {
    'use strict';

    const ORDER_WIDGET_CONFIG = {
        turnstiledivId: 'order-turnstile',
        sitekey: '3x00000000000000000000FF'
    };

    function initContactWidget() {
        const turnstileDiv = document.getElementById(ORDER_WIDGET_CONFIG.turnstiledivId);

        if (!turnstileDiv) {
            console.warn('[Order Widget] Turnstile container not found');
            return;
        }

        // Wait for Turnstile API to be available
        if (typeof window.turnstile === 'undefined') {
            console.warn('[Order Widget] Turnstile API not loaded yet');
            // Retry after a short delay
            setTimeout(initContactWidget, 100);
            return;
        }

        // Render Turnstile widget explicitly (not auto-render to avoid conflicts with order form)
        window.turnstile.render(`#${ORDER_WIDGET_CONFIG.turnstiledivId}`, {
            sitekey: ORDER_WIDGET_CONFIG.sitekey,
            theme: getTheme(),
        });
    }

    function mutationObserver() {
        // Listen for theme changes and update Turnstile theme accordingly
        const observer = new MutationObserver(() => {
            const turnstileDiv = document.querySelector('form#contactForm .cf-turnstile');
            if (turnstileDiv && window.turnstile) {
                window.turnstile.remove(turnstileDiv);
                initContactWidget();
            }
        });

        observer.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', () => {
            initContactWidget();
            mutationObserver();
        });
    } else {
        initContactWidget();
        mutationObserver();
    }

})();