document.getElementById('contactForm').addEventListener('submit', async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);

    const payload = {
        name: document.getElementById('name').value,
        contact: document.getElementById('contact').value,
        message: document.getElementById('message').value,
        // This is the token generated by Turnstile
        turnstileToken: formData.get('cf-turnstile-response')
    };

    // 
    const response = await fetch('https://late-pond-aa61.ivan-kuchin-13d.workers.dev', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
    });
    const result = await response.json();

    console.log(result);
    if (result.status === "sent") {
        console.log("Message sent successfully!");
    } else {
        console.log("Failed to send message: " + result.error);
    }
});